name: mis_lab4
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  flutter_map: ^6.2.1
  flutter_map_marker_popup: ^5.0.0
  geolocator: ^9.0.0
  table_calendar: ^3.0.8
  intl: ^0.18.1
  latlong2: ^0.9.0
  flutter_polyline_points: ^2.1.0
  image_picker: ^1.1.2
  awesome_notifications: ^0.7.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true